spring:
  application:
    name: product-service
  config:
    activate:
      on-profile: docker

server:
  port: 7200

logging:
  level:
    root: INFO
    com.ductlmse.microservices.core.product: DEBUG

---
spring:
  config:
    activate:
      on-profile: docker

server:
  port: 8080