spring:
  application:
    name: review-service
  datasource:
    username: user
    url: jdbc:mysql://localhost:3306
    password: pwd



---
spring:
  config:
    activate:
      on-profile: docker

server:
  port: 8080